name: Automate project columns

on: [issues, pull_request]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move new issues into project
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: alex-page/github-project-automation-plus@master
        with:
          project: 16th August - 26th September
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
